- id: cluster-configure-ui
  title: UI
  content: TODO

- id: cluster-configure-code
  title: Code
  content: |
    <figure><figcaption>eks_configuration.yml</figcaption>
      <pre>
          <code class="language-yml">
          # Configure CIS Benchmark compliance
          cis:
            enabled: true

          # Choose from istio, consul-connect, aws-app-mesh
          service_mesh: "istio"

          # Choose from flux or argocd
          cicd: "argocd"

          # Choose from argocd or lens
          self_service: "argocd"

          # Choose from prometheus, datadog, cloudwatch
          metric_aggregation: "prometheus"

          # Choose from elastic, datadog, cloudwatch
          log_aggregation: "elastic"

          # Configure various common utilities
          cluster_autoscaler:
            enabled: true

          harbor:
            enabled: true

          opa:
            enable_kubernetes_rules: true
            enable_terraform_rules: true

          sealed_secrets:
            enabled: true

          external_dns:
            enabled: true
            domains:
              - env: "dev"
                domain: "gruntwork-dev.com"
              - env: "prod"
                domain: "gruntwork.io"
          </code>
      </pre>
    </figure>
