- title: Production Deployment Guides
  url: "/guides"
  image: /assets/img/training-resources/production-deployment-guides.png
  description: |
    Step-by-step guides that show you how to go to production on top of AWS. Learn how to deploy a
    production-grade Kubernetes cluster on AWS, how to configure your AWS account structure, how to deploy VPCs, and
    much more.
  bg_color: blue

- title: Automated Testing for Terraform, Docker, Packer, Kubernetes, and More
  url: "https://www.infoq.com/presentations/automated-testing-terraform-docker-packer/"
  image: /assets/img/training-resources/testing-talk-cover-slide-medium.png
  description: |
    This talk from QCon SF is a step-by-step, live-coding class on how to write automated tests for infrastructure
    code, including the code you write for use with tools such as Terraform, Kubernetes, Docker, and Packer. Topics
    covered include unit tests, integration tests, end-to-end tests, test parallelism, retries, error handling, static
    analysis, and more.
  bg_color: purple

- title: How to Build an End to End Production-Grade Architecture on AWS
  url: "https://blog.gruntwork.io/how-to-build-an-end-to-end-production-grade-architecture-on-aws-part-1-eae8eeb41fec"
  image: /assets/img/training-resources/ref-arch.png
  description: |
    This blog series will take you on a guided tour of a modern production-grade architecture for AWS. You’ll see what
    an end-to-end solution looks like, including how to combine Kubernetes, AWS VPCs, data stores, CI/CD, secrets
    management, and a whole lot more to deploy your applications for production use. We’ll cover both the specific
    choices and patterns employed in the architecture, as well as why some of those patterns make sense in the context
    of AWS.
  bg_color: orange

- title: Reusable, composable, battle-tested Terraform modules
  url: "https://www.ybrikman.com/writing/2017/10/13/reusable-composable-battle-tested-terraform-modules/"
  image: /assets/img/training-resources/training-terraform-modules.png
  description: |
    A talk from HashiConf 2017  that will show you how Terraform modules work, how to design modules so they are highly
    configurable and reusable, how to write automated tests for your Terraform code, and how you can use modules to
    build your entire tech stack on top of proven, battle-tested infrastructure code—in minutes.
  bg_color: purple

- title: Terraform Up &amp; Running
  url: "https://www.terraformupandrunning.com"
  image: /assets/img/training-resources/training-terraform-up-and-running.png
  description: |
    This book is the fastest way to get up and running with Terraform. You'll go from deploying a basic "Hello, World"
    Terraform example all the way up to running a full tech stack (server cluster, load balancer, database) that can
    support a large amount of traffic and a large team of developers—all in the span of just a few chapters.
  bg_color: blue

- title: Lessons learned from writing over 300,000 lines of infrastructure code
  url: "https://blog.gruntwork.io/5-lessons-learned-from-writing-over-300-000-lines-of-infrastructure-code-36ba7fadeac1"
  image: /assets/img/training-resources/lessons-learned-300k.png
  description: |
    This talk from HashiConf 2018 is a concise masterclass on how to write infrastructure code. I share key lessons
    from the "Infrastructure Cookbook" we developed at Gruntwork while creating and maintaining a library of over
    300,000 lines of infrastructure code that's used in production by hundreds of companies. Come and hear our war
    stories, laugh about all the mistakes we’ve made along the way, and learn what Terraform, Packer, Docker, and Go
    look like in the wild.
  bg_color: purple

- title: A Comprehensive Guide to Building a Scalable Web App on Amazon Web Services
  url: "https://www.airpair.com/aws/posts/building-a-scalable-web-app-on-amazon-web-services-p1"
  image: /assets/img/training-resources/training-a-comprehensive-guide.png
  description: |
    A definitive guide on how to think about building apps on AWS, including how to think about scalability and high
    availability, an overview of how to use the most important AWS services, and an introduction to cloud-native
    architecture.
  bg_color: orange

- title: A Comprehensive Guide to Terraform
  url: "https://blog.gruntwork.io/a-comprehensive-guide-to-terraform-b3d32832baca"
  image: /assets/img/training-resources/training-comprehensive-guide-terraform.png
  description: |
    Our blog post series on how to use Terraform that covers how Terraform compares to Chef, Puppet, Ansible, and
    CloudFormation, introduces Terraform syntax, discuss how to manage Terraform state, shows how to build reusable
    infrastructure with Terraform modules, and introduces a workflow for how to use Terraform as a team.
  bg_color: purple

- title: The Production Readiness Checklist for AWS
  url: "/devops-checklist/"
  image: /assets/img/training-resources/devops-checklist.png
  description: |
    This checklist is your guide to the best practices for deploying secure, scalable, and highly available
    infrastructure in AWS. Before you go live, go through each item, and make sure you haven't missed anything
    important!
  bg_color: blue

- title: "Running microservices on AWS using Docker, Terraform, and ECS"
  url: "https://www.ybrikman.com/writing/2016/03/31/infrastructure-as-code-microservices-aws-docker-terraform-ecs/"
  image: /assets/img/training-resources/training-infrastructure-as-code.png
  description: |
    A talk from DevOps Italia 2016 that shows how to use Terraform, Docker, and Amazon's EC2 Container Service to run
    microservices in AWS.
  bg_color: orange

- title: A Comprehensive Guide to AWS Authentication
  url: "https://blog.gruntwork.io/a-comprehensive-guide-to-authenticating-to-aws-on-the-command-line-63656a686799"
  image: /assets/img/training-resources/keys.jpg
  description: |
    Our blog post series on how to authenticate to AWS on the command-line, including how to use Access Keys, IAM
    Roles, MFA, the Credentials File, Environment Eariables, and Instance Metadata.
  bg_color: blue

- title: "Terratest: a swiss army knife for testing infrastructure code"
  url: "https://blog.gruntwork.io/open-sourcing-terratest-a-swiss-army-knife-for-testing-infrastructure-code-5d883336fcd5"
  image: /assets/img/training-resources/swiss-army-knife.jpg
  description: |
    Terratest is a Go library that makes it easier to write automated tests for your infrastructure code. It provides a
    variety of helper functions and patterns for testing Terraform code, Docker images, Packer templates, AWS resources,
    and much more.
  bg_color: purple

- title: "Agility Requires Safety"
  url: "https://www.ybrikman.com/writing/2016/02/14/agility-requires-safety/"
  image: /assets/img/training-resources/training-agility-requires-safety.png
  description: |
    To go faster in a car, you need not only a powerful engine, but also safety mechanisms like brakes, air bags, and
    seat belts. This is a talk about the safety mechanisms that allow you to build software faster, including
    continuous integration, microservices, feature toggles, and canary deployments.
  bg_color: orange

- title: "Choosing the Right Framework for Running Docker Containers in Production"
  url: "https://joshpadnick.com/2015/09/01/my-talk-on-choosing-the-right-framework-for-running-docker-containers-in-production/"
  image: /assets/img/training-resources/training-choosing-framework-docker.png
  description: |
    A talk from Iterate.PHX on choosing the right framework for running docker containers in production. Goes over the
    trade-offs between Amazon ECS, Docker Swarm, CoreOS Fleet, Deis, Flynn, Mesos, and Kubernetes.
  bg_color: purple
