- title: A Crash Course on Terraform
  description: Learn how to manage infrastructure as code using Terraform through a series of live coding exercises.
  url: "https://training.gruntwork.io/courses/terraform/lectures/3429337"
  author: Josh Padnick & Yoriyasu Yano
  author_thumbnail: /assets/img/josh-yori-thumbnail.png
  course_thumbnail: /assets/img/terraform-logo-training.png
  course_thumbnail_height: 170
  videos: 30
  duration: 92 minutes
  bg_color: purple


- title: Infrastructure Module Cookbook
  description: A guide to building reusable, production-grade, battle-tested infrastructure code.
  url: "https://training.gruntwork.io/courses/infrastructure-module-cookbook/lectures/9081297"
  author: Yevgeniy Brikman
  author_thumbnail: /assets/img/yevgeniy-thumbnail.png
  course_thumbnail: /assets/img/grunty-boxes.png
  course_thumbnail_height: 234
  videos: 8
  duration: 141 minutes
  bg_color: blue

- title: A Crash Course on Docker &amp; Packer
  description: Learn how to package your code using Packer and Docker into immutable images that run exactly the same way in all environments.
  url: "https://training.gruntwork.io/courses/a-crash-course-on-docker-packer/lectures/4247382"
  author: Yevgeniy Brikman
  author_thumbnail: /assets/img/yevgeniy-thumbnail.png
  course_thumbnail: /assets/img/docker-packer-training.png
  course_thumbnail_height: 98
  videos: 40
  duration: 95 minutes
  bg_color: orange